### ISSUE TITLE
Running CLI command on README example doesnt output the correct thing

### ISSUE THREAD

**Issue by Heagan** [labd/schema-generate#7]
Hey, sorry, I'm new to this, I've been trying to get this package working but when I run it on anyfile it shows the same output:
`yarn schema-generate graphql example.ts`
```
directive @markdown on FIELD_DEFINITION
scalar AmplienceLocalizedString
```

I ran it on a file with the example on the README, I didnt add or remove anything, I'm wondering if thats why?

maybe its failing because my node version is the latest version 12

**Comment by korsvanloon** [comment]
Hello Heagan, and thanks for your interest!
This package is lacking a bit in documentation, excuse me.
In this case, the generator only looks for _exported_ types and interfaces.

For more advanced cases that actually work, I would like to refer you to the testdata folder of both [graphql](https://github.com/labd/schema-generate/tree/master/test/graphql/testdata) and [amplience](https://github.com/labd/schema-generate/tree/master/test/amplience/testdata).

I will update the README as well :)
